### ISSUE TITLE
Falcon.init中project参数应为可选

### ISSUE THREAD

**Issue by malash** [CatTail/node-open-falcon#2]
根据[README中的代码](https://github.com/CatTail/node-open-falcon#usage)，`Falcon.init`函数的第二个参数project应该为可选参数，但事实上如果没有指定project，会导致tag：`project=undefined`被发送。
问题出在：[https://github.com/CatTail/node-open-falcon/blob/master/index.js#L54](https://github.com/CatTail/node-open-falcon/blob/master/index.js#L54)，应对`Falcon.PROJECT`进行判断。

**Comment by CatTail** [comment]
Fixed in 60e6082c78e574778133221279df107ae0f117d3. Use version 1.3.4
